version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ../Dockerfile-composer.dockerfile
    container_name: symfony_app
    volumes:
      - .:/var/www/symfony:delegated
      - /var/www/symfony/var
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://symfony:password@db:3306/symfony?serverVersion=mariadb-10.5.0"

  db:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: symfony
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db
volumes:
  db_data: {}